name: Deploy to Github Pages

on:
 push:
  branches:
   - main

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout Repository
    uses: actions/checkout@v2

  - name: Set up Python
    uses: actions/setup-python@v2
    with:
     python-version: 3.x

  - name: Install Dependencies
    run: |
     python -m pip install --upgrade pip
     pip install -r requirements.txt

  - name: Run Python Script
    run: python my.py

  - name: Deploy to Github Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
     github_token: ${{ secrets.GH_TOKEN }}
     publish_dir: ./your_output_directory
    
